import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Card.module.css'
import { getAllPostIds, getCardData } from '../../lib/cards'
import Card from '../../components/Card'

export async function getStaticProps({ params }) {
  const postData = await getCardData(params.id)
  return {
    props: {
      postData
    }
  }
}

export default function CardPage(props) {
    return (
        <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
              <main className={styles.main}>
              <h1 className={styles.title}>
                Card #{props.postData.id} - {props.postData.name} the {props.postData.class}
              </h1>
      
              <p className={styles.description}>
               
              </p>
              <div className={styles.grid}>
              <Card 
            name={props.postData.name}
            race="human"
            class={props.postData.class}
            health={props.postData.health}
            armor={props.postData.armor}
            mana={props.postData.mana}
            strength={props.postData.strength}
            agility={props.postData.agility}
            intelligence={props.postData.intelligence}
            damage={props.postData.damage}
            crit={props.postData.crit}
            magic={props.postData.magic}
            avatar={props.postData.avatar}
            lvl={props.postData.lvl}
            attrib={props.postData.attrib}
            />
      </div>
      <Link href="/">
          <a>&larr; BACK TO HOME</a>
        </Link>
              </main>
              </div>
    )
  }

  export async function getStaticPaths() {
    const paths = getAllPostIds()
    return {
      paths,
      fallback: false
    }
  }